version: "3.8"
services:
  bind-dns:
    build: 
      context: bind-dns/
    volumes: 
      - "./bind-dns/config/named.conf:/etc/named.conf"
    networks: 
      - private-sub


  bastion:
    build:
      context: bastion/
    tty: true
    networks: 
      - private-sub
      - public-sub


networks:
  private-sub:
  public-sub: