version: "3.8"
services:
  bind-dns:
    build: 
      context: bind-dns/
    volumes: 
      - "./bind-dns/config/named.conf:/etc/named.conf:ro"
    networks: 
      - internal

  bastion:
    build:
      context: bastion/
    tty: true
    networks: 
      - internal
      - bridge
    

networks:
  internal:
  bridge: